dist: xenial   # required for Python >= 3.7

language: python
python:
  - "3.7"
install:
  - "pip install -r .travis/requirements.txt"

# Safelist
branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
