# This will run on Travis' 'new' container-based infrastructure
sudo: false

language: python
python:
  - "3.7"
install:
  - "pip install -r .travis/requirements.txt"

# Blacklist
branches:
  only:
    - master
