dist: xenial   # required for Python >= 3.7

language: python
python:
  - "3.7"

# safelist
branches:
  only:
    - master

script:
- .travis/prepare-docs.py
- git add _sidebar.md

deploy:
  provider: pages
  skip_cleanup: true
  target-branch: gh-pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master
