---
title: "KaplanMeier"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Color map
```{r}
library(RColorBrewer)
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
col_vector = unique(col_vector)
```

# Read in data
```{r}
library(data.table)
surv_dat = fread('D:/Jana/PhD/BBsnippets/surv_dat.csv',header = T)
head(surv_dat)

```

# Prepare data for Kaplan-Meier survival curves
```{r}
library(stringr)
library(survival)

#Censoring for overall survival
surv_dat$censoringOS[str_detect(surv_dat$Patientstatus,'death by primary disease')] = 1
surv_dat$censoringOS[is.na(surv_dat$censoringOS)] = 0

#Censoring for disease free survival
surv_dat$censoringDFS[str_detect(surv_dat$Patientstatus,'alive w metastases')] = 1
surv_dat$censoringDFS[surv_dat$OSmonth > surv_dat$DFSmonth] = 1 
surv_dat$censoringDFS[is.na(surv_dat$censoringDFS)] = 0

#Kaplan-Meiers for overall survival or disease free survival
SurvObj <- Surv(surv_dat$OSmonth, surv_dat$censoringOS) # or DFSmonth, censoringDFS
surv_dat$grade = as.factor(surv_dat$grade)
km.as.groups <- survfit(SurvObj ~ surv_dat$grade)
km.as.one <- survfit(SurvObj ~ 1)

```

# Plot all patient group survival curves in one panel, plus overall curve across all patients in black
```{r}

# #Write out to pdf
# pdf('D:/Jana/PhD/BBsnippets/KaplanMeier_all.pdf',width = 10,height = 10)
# plot(km.as.groups,mark.time = T,col = col_vector[as.numeric(levels(surv_dat$grade))])
# par(new=TRUE)
# plot(km.as.one,mark.time = T,col = "black")
# legend(1,1,levels(surv_dat$grade),col_vector[as.numeric(levels(surv_dat$grade))])
# dev.off()

plot(km.as.groups,mark.time = T,col = col_vector[as.numeric(levels(surv_dat$grade))])
par(new=TRUE)
plot(km.as.one,mark.time = T,col = "black")
legend(1,1,levels(surv_dat$grade),col_vector[as.numeric(levels(surv_dat$grade))])

```

# Plot each patient group survival curve in a separate panel
# together with overall curve across all patients in black
```{r}

# #write out to pdf
# pdf('D:/Jana/PhD/BBsnippets/KaplanMeier.pdf',width = 20,height = 20)
# par(mfrow=c(4,5))
# for (i in levels(surv_dat$grade)){
#   group_dat = subset(surv_dat, surv_dat$grade == i)
#   SurvObj_group <- Surv(group_dat$OSmonth, group_dat$censoringOS)
#   km.group <- survfit(SurvObj_group ~ 1)
#   plot(km.group,mark.time = T,col = col_vector[as.numeric(i)],xlim=range(1:242))
#   par(new=TRUE)
#   plot(km.as.one,mark.time = T,col = "black",xlim=range(1:242))
#   legend("bottomleft",1,i,col_vector[as.numeric(i)], cex=3)
# }
# dev.off()


for (i in levels(surv_dat$grade)){
  group_dat = subset(surv_dat, surv_dat$grade == i)
  SurvObj_group <- Surv(group_dat$OSmonth, group_dat$censoringOS)
  km.group <- survfit(SurvObj_group ~ 1)
  plot(km.group,mark.time = T,col = col_vector[as.numeric(i)],xlim=range(1:242))
  par(new=TRUE)
  plot(km.as.one,mark.time = T,col = "black",xlim=range(1:242))
  legend("bottomleft",1,i,col_vector[as.numeric(i)], cex=3)
}


```

```{r}
sessionInfo()
```
